2024-02-21 04:09:54,273 INFO    MainThread:10666 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-21 04:09:54,273 INFO    MainThread:10666 [wandb_setup.py:_flush():76] Configure stats pid to 10666
2024-02-21 04:09:54,273 INFO    MainThread:10666 [wandb_setup.py:_flush():76] Loading settings from /home/kjk/.config/wandb/settings
2024-02-21 04:09:54,273 INFO    MainThread:10666 [wandb_setup.py:_flush():76] Loading settings from /home/kjk/Documents/Workspace/NeuralNetfromScratch/src/models/wandb/settings
2024-02-21 04:09:54,273 INFO    MainThread:10666 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-21 04:09:54,273 INFO    MainThread:10666 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-21 04:09:54,273 INFO    MainThread:10666 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-21 04:09:54,273 INFO    MainThread:10666 [wandb_init.py:_log_setup():526] Logging user logs to /home/kjk/Documents/Workspace/NeuralNetfromScratch/src/models/wandb/run-20240221_040954-et0c7tx4/logs/debug.log
2024-02-21 04:09:54,273 INFO    MainThread:10666 [wandb_init.py:_log_setup():527] Logging internal logs to /home/kjk/Documents/Workspace/NeuralNetfromScratch/src/models/wandb/run-20240221_040954-et0c7tx4/logs/debug-internal.log
2024-02-21 04:09:54,273 INFO    MainThread:10666 [wandb_init.py:init():566] calling init triggers
2024-02-21 04:09:54,273 INFO    MainThread:10666 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-02-21 04:09:54,273 INFO    MainThread:10666 [wandb_init.py:init():591] re-initializing run, found existing run on stack: 7emmjx0m
2024-02-21 04:09:54,274 INFO    MainThread:10666 [wandb_run.py:_finish():1970] finishing run kimkj/mnist-model-evaluation/7emmjx0m
2024-02-21 04:09:54,275 INFO    MainThread:10666 [jupyter.py:save_history():445] not saving jupyter history
2024-02-21 04:09:54,275 INFO    MainThread:10666 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-02-21 04:09:54,275 INFO    MainThread:10666 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-02-21 04:09:54,275 INFO    MainThread:10666 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-02-21 04:09:54,275 INFO    MainThread:10666 [wandb_run.py:_restore():2193] restore
2024-02-21 04:09:54,275 INFO    MainThread:10666 [wandb_run.py:_restore():2199] restore done
2024-02-21 04:09:58,570 INFO    MainThread:10666 [wandb_run.py:_footer_history_summary_info():3866] rendering history
2024-02-21 04:09:58,571 INFO    MainThread:10666 [wandb_run.py:_footer_history_summary_info():3898] rendering summary
2024-02-21 04:09:58,574 INFO    MainThread:10666 [wandb_run.py:_footer_sync_info():3825] logging synced files
2024-02-21 04:09:58,676 INFO    MainThread:10666 [wandb_init.py:init():616] starting backend
2024-02-21 04:09:58,676 INFO    MainThread:10666 [wandb_init.py:init():620] setting up manager
2024-02-21 04:09:58,682 INFO    MainThread:10666 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-02-21 04:09:58,682 INFO    MainThread:10666 [wandb_init.py:init():628] backend started and connected
2024-02-21 04:09:58,696 INFO    MainThread:10666 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-02-21 04:09:58,696 INFO    MainThread:10666 [wandb_init.py:init():720] updated telemetry
2024-02-21 04:09:58,698 INFO    MainThread:10666 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-21 04:09:59,851 INFO    MainThread:10666 [wandb_run.py:_on_init():2262] communicating current version
2024-02-21 04:09:59,910 INFO    MainThread:10666 [wandb_run.py:_on_init():2271] got version response 
2024-02-21 04:09:59,910 INFO    MainThread:10666 [wandb_init.py:init():804] starting run threads in backend
2024-02-21 04:09:59,927 INFO    MainThread:10666 [wandb_run.py:_console_start():2241] atexit reg
2024-02-21 04:09:59,927 INFO    MainThread:10666 [wandb_run.py:_redirect():2096] redirect: wrap_raw
2024-02-21 04:09:59,927 INFO    MainThread:10666 [wandb_run.py:_redirect():2161] Wrapping output streams.
2024-02-21 04:09:59,928 INFO    MainThread:10666 [wandb_run.py:_redirect():2186] Redirects installed.
2024-02-21 04:09:59,928 INFO    MainThread:10666 [wandb_init.py:init():847] run started, returning control to user process
2024-02-21 04:11:35,894 INFO    MainThread:10666 [wandb_watch.py:watch():51] Watching
2024-02-21 04:12:57,204 INFO    MainThread:10666 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-21 04:12:57,204 INFO    MainThread:10666 [wandb_setup.py:_flush():76] Configure stats pid to 10666
2024-02-21 04:12:57,204 INFO    MainThread:10666 [wandb_setup.py:_flush():76] Loading settings from /home/kjk/.config/wandb/settings
2024-02-21 04:12:57,204 INFO    MainThread:10666 [wandb_setup.py:_flush():76] Loading settings from /home/kjk/Documents/Workspace/NeuralNetfromScratch/src/models/wandb/settings
2024-02-21 04:12:57,204 INFO    MainThread:10666 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-21 04:12:57,204 INFO    MainThread:10666 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-21 04:12:57,204 INFO    MainThread:10666 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-21 04:12:57,205 INFO    MainThread:10666 [wandb_init.py:_log_setup():526] Logging user logs to /home/kjk/Documents/Workspace/NeuralNetfromScratch/src/models/wandb/run-20240221_041257-ptr49hky/logs/debug.log
2024-02-21 04:12:57,205 INFO    MainThread:10666 [wandb_init.py:_log_setup():527] Logging internal logs to /home/kjk/Documents/Workspace/NeuralNetfromScratch/src/models/wandb/run-20240221_041257-ptr49hky/logs/debug-internal.log
2024-02-21 04:12:57,205 INFO    MainThread:10666 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f4a903bea70>
2024-02-21 04:12:57,205 INFO    MainThread:10666 [wandb_init.py:init():566] calling init triggers
2024-02-21 04:12:57,205 INFO    MainThread:10666 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-02-21 04:12:57,205 INFO    MainThread:10666 [wandb_init.py:init():591] re-initializing run, found existing run on stack: et0c7tx4
2024-02-21 04:12:57,206 INFO    MainThread:10666 [wandb_run.py:_finish():1970] finishing run kimkj/mnist-model-evaluation/et0c7tx4
2024-02-21 04:12:57,206 INFO    MainThread:10666 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-02-21 04:12:57,206 INFO    MainThread:10666 [wandb_run.py:_restore():2193] restore
2024-02-21 04:12:57,206 INFO    MainThread:10666 [wandb_run.py:_restore():2199] restore done
2024-02-21 04:12:58,833 WARNING MsgRouterThr:10666 [router.py:message_loop():77] message_loop has been closed
2024-02-21 04:13:08,210 INFO    MainThread:10666 [wandb_run.py:_restore():2193] restore
2024-02-21 04:13:08,210 INFO    MainThread:10666 [wandb_run.py:_restore():2199] restore done
2024-02-21 04:13:08,272 ERROR   MainThread:10666 [wandb_init.py:init():1204] error
Traceback (most recent call last):
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2219, in _atexit_cleanup
    self._on_finish()
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2474, in _on_finish
    _ = exit_handle.wait(timeout=-1, on_progress=self._on_progress_exit)
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 298, in wait
    on_probe(probe_handle)
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2436, in _on_probe_exit
    result = handle.wait(timeout=0, release=False)
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 281, in wait
    raise MailboxError("transport failed")
wandb.sdk.lib.mailbox.MailboxError: transport failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 601, in init
    latest_run.finish()
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 420, in wrapper
    return func(self, *args, **kwargs)
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 361, in wrapper
    return func(self, *args, **kwargs)
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1961, in finish
    return self._finish(exit_code, quiet)
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1976, in _finish
    self._atexit_cleanup(exit_code=exit_code)
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2230, in _atexit_cleanup
    self._backend.cleanup()
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/backend/backend.py", line 232, in cleanup
    self.interface.join()
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 547, in join
    super().join()
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 710, in join
    _ = self._communicate_shutdown()
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 440, in _communicate_shutdown
    _ = self._communicate(record)
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 300, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 60, in _communicate_async
    future = self._router.send_and_receive(rec, local=local)
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/interface/router.py", line 94, in send_and_receive
    self._send_message(rec)
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 36, in _send_message
    self._sock_client.send_record_communicate(record)
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 216, in send_record_communicate
    self.send_server_request(server_req)
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2024-02-21 04:13:16,861 INFO    MainThread:10666 [wandb_run.py:_finish():1970] finishing run kimkj/mnist-model-evaluation/et0c7tx4
